//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBödev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalık
    {
        public int Id { get; set; }
        public string KullanıcıTc { get; set; }
        public string HastalıkAdı { get; set; }
        public string Açıklama { get; set; }
        public string Belirtiler { get; set; }
        public string Bölümü { get; set; }
        public string RiskFaktörü { get; set; }
        public string Teşhis { get; set; }
        public string İstenilenTestler { get; set; }
        public string Verilenİlaç { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
