//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBödev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlaç
    {
        public int Id { get; set; }
        public string KullanıcıTc { get; set; }
        public Nullable<int> İlaçNo { get; set; }
        public string İlaçAdı { get; set; }
        public Nullable<System.DateTime> SonKullanmaTarihi { get; set; }
        public string Dozaj { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
