//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBödev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int Id { get; set; }
        public string KullanıcıTc { get; set; }
        public string Şifre { get; set; }
        public string AdSoyad { get; set; }
        public string Cinsiyet { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DoğumTarihi { get; set; }
        public string Rol { get; set; }
    
        public virtual Hastalık Hastalık { get; set; }
        public virtual İlaç İlaç { get; set; }
        public virtual Tahlil Tahlil { get; set; }
    }
}
