//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBödev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tahlil
    {
        public int Id { get; set; }
        public string KullanıcıTc { get; set; }
        public Nullable<int> TestNo { get; set; }
        public string TestAdı { get; set; }
        public Nullable<System.DateTime> TestTarihi { get; set; }
        public string SorumluDoktor { get; set; }
        public string Açıklama { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
